version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password
    ports:
    # AMQP protocol port
    - "5672:5672"
    # HTTP management UI
    - "15672:15672"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "payment"
    volumes:
      - db-data:/var/lib/postgresql/data

  monolith:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/payment
      - PORT=3000
      - JWT_SECRET=s3cr3t
      - NODE_ENV=dev
    ports:
      - "3000:3000"
    command: "sh -c 'npm install; npm run start'"

volumes:
  db-data: {}
